version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/LunaDB
      - APP_URL=http://127.0.0.1
      - BETTER_AUTH_SECRET=WUxnvEvKyIVDfEpSmCp8BfnnYTxUPSRa
      - BETTER_AUTH_URL=http://127.0.0.1:8000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_URL: http://127.0.0.1:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
